### ISSUE TITLE
MergeTaxonomies seems like it's not used anywhere in the package

### ISSUE THREAD

**Issue by sckott** [ropensci/reol#4]
@bomeara @bbanbury And there's no examples of its use, and I don't see it used anywhere internally in the pacakge. Should it be removed?

**Comment by bbanbury** [comment]
It is used internally for combining hierarchy tables (See CombineHierarchyInfo > MakeTreeData > MakeHierarchyTree). It is needed for when some taxa have information at a taxonomic level and another does not.

**Comment by sckott** [comment]
@bbanbury ah, sorry i missed that. But it doesn't seem like there's a good reason to export it. If there is, would be good to give some examples of its use

**Comment by bbanbury** [comment]
That is fine, it doesn't have to be exported.  I typically just export everything.  
I think it is best as an internal function without examples.

**Comment by sckott** [comment]
What about other functions only used internally. Okay to make those not exported as well?  I argue this because we generally only export functions that are most definitely for users. See Hadley's section on exports http://r-pkgs.had.co.nz/namespace.html#exports - e.g., 

> Generally, it’s better to export too little than too much

**Comment by bbanbury** [comment]
Totally fine, it really makes no difference to me (unless Brian disagrees). I personally hate trying to sniff out internal functions, and this is why I simply export everything, but I am happy to go along with whatever the rOpenSci crowd feels is best.

**Comment by bomeara** [comment]
I lean towards more liberality in exporting than Hadley's (I'd have a
"likely to be useful" rather than "needed" criterion, and rely on good
naming to reduce collisions), but am totally fine with clearly internal
functions not being exported.

Best,
Brian

_______________________________________
Brian O'Meara
Assistant Professor
Dept. of Ecology & Evolutionary Biology
U. of Tennessee, Knoxville
http://www.brianomeara.info

Postdoc collaborators wanted: http://nimbios.org/postdocs/
Calendar: http://www.brianomeara.info/calendars/omeara

**Comment by karthik** [comment]
> Totally fine, it really makes no difference to me (unless Brian disagrees). I personally hate trying to sniff out internal functions, and this is why I simply export everything, but I am happy to go along with whatever the rOpenSci crowd feels is best.

From our experience it hasn't been such a great idea to export everything. Creates a lot of namespace clutter. It makes life harder for casual users (_which one of these variants do I use?_) and doesn't really help out power users since they can suss out what's available by looking over the source. So not a hard rule yet from out side but we strongly recommend not exporting everything as a default.

**Comment by maelle** [comment]
This package is no longer maintained and has been archived on CRAN.
