### ISSUE TITLE
Setting exact=FALSE produces null results

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/reol#6]
Something has been wonky since the list EOL api update.  Try the following

```
 DownloadSearchedTaxa("Laminaria digitata", to.file=FALSE, exact=TRUE)
```

Works fine, but

```
 DownloadSearchedTaxa("Laminaria digitata", to.file=FALSE, exact=FALSE)
```

produces a `NULL` result.

The helpfile demo also produces some NULLs in places where they should not be. Has fuzzy matching changed somehow?

**Comment by bbanbury** [comment]
Looks like it might be an issue with the web server. When I use safari, I get nothing for either, but when I use google chrome, I get pages back for both calls.  Weird.
http://eol.org/api/search/1.0.xml?q=Laminaria%20digitata&exact=TRUE&page=1
http://eol.org/api/search/1.0.xml?q=Laminaria%20digitata&exact=FALSE&page=1

These are what Reol uses to gather data, but via the RCurl package rather than a web browser. It looks like RCurl is having a hard time gathering the data back. I will have to dig a little deeper later when I have some time...

**Comment by maelle** [comment]
This package is no longer maintained and has been archived on CRAN.
